name: ArathiBasin
author: SnowGears
description: Capture the point mini-game based on Arathi Basin from World of Warcraft!
version: 1.0.9
api-version: 1.13
main: com.snowgears.arathibasin.ArathiBasin
softdepend: [PlaceholderAPI]
commands:
   arathi:
      description: Different commands pertaining to plugin
      usage: /<command>
   structure:
      description: This command is used for setting up a world to be used for the Arathi game.
      usage: /<command>
permissions:
    arathi.play:
        description: Allows player to play the arathi basin mini-game
        default: op
    arathi.operator:
        description: Allows player use all operator actions associated with plugin
        default: op
